services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/gotenks/.config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: Asia/Kolkata
  lms:
    image: lmscommunity/lyrionmusicserver:latest
    container_name: lms
    network_mode: host
    volumes:
      - ${USERDIR:-$HOME}/Data/KPOP_FLACs:/music:ro
      - ${USERDIR:-$HOME}/docker/logitechmediaserver/config:/config:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
